version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: alquiler_futbolistas
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./server
    command: npm run dev
    volumes:
      - ./server:/app
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://usuario:contraseña@db:5432/alquiler_futbolistas
    depends_on:
      - db
  frontend:
    build: ./client
    command: npm start
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000/api
    depends_on:
      - backend
volumes:
  db_data: 